// Imports
import mongoose from "mongoose";

// Schema
const BuildingSchema = mongoose.Schema({
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "users",
  },
  property_code: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "properties",
  },
  building_code: { type: String },
  name: { type: String },
  street_address: { type: String },
  zip_code: { type: String },
  city: { type: String },
  construction_year: { type: String },
  listed_building: { type: String },
  u_operation_type: { type: String },
  u_facade: { type: String },
  u_windows: { type: String },
  u_entrance: { type: String },
  u_roof: { type: String },
  u_foundation: { type: String },
  u_electricity: { type: String },
  u_ventilation: { type: String },
  u_heating: { type: String },
  u_doors: { type: String },
  u_heat_dist: { type: String },
  u_waste_disposal: { type: String },
  miscellaneous: { type: String },
  u_elevator: { type: String },
  responsible_user: {
    type: String,
    set: (value) => value?.toLowerCase(),
  },
  latitude: { type: String },
  longitude: { type: String },
  changed_by: { type: String },
  owner: { type: String },
  no_of_windows: { type: String },
  no_of_entrance_doors: { type: String },
  no_of_doors: { type: String },
  no_of_light_fixtures: { type: String },
  no_of_light_posts: { type: String },
  no_of_laundries: { type: String },
  no_of_balconies: { type: String },
  no_of_ventilation_units: { type: String },
  no_of_stairwells: { type: String },
  no_of_light_fixtures: { type: String },
  no_of_charging_posts: { type: String },
  building_area: { type: String },
  roof_area: { type: String },
  no_of_appartments: { type: String },
  no_of_elevators: { type: String },
  facade_area: { type: String },
  // ................................
  total_rent: { type: String },
  area_boa: { type: String },
  area_bia: { type: String },
  area_bta: { type: String },
  area_bra: { type: String },
  area_loa: { type: String },
  area_ova: { type: String },
  area_a_temp: { type: String },
  area_parking_space: { type: String },
  let_area_percent: { type: String },
  no_of_floors: { type: String },
  no_of_apartments: { type: String },
  area_heating: { type: String },
  area_tak_yta: { type: String },
  area_fasad_yta: { type: String },
  change_by: { type: String },
  image: {
    link: { type: String },
    createdAt: { type: Date, default: new Date() },
    format: { type: String },
    dimensions: { type: String },
    key: { type: String },
  },
});

// Export
export default mongoose.model("buildings", BuildingSchema);
