// Imports
import mongoose from "mongoose";

// Schema
const ComponentSchema = mongoose.Schema({
  property_code: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "properties",
  },
  building_code: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "buildings",
  },
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "users",
  },
  component_code: { type: String },
  name: { type: String },
  other_text: { type: String },
  attendance_text: { type: String },
  maintenance_text: { type: String },
  contracted: { type: String },
  model: { type: String },
  manufacturer: { type: String },
  reconstruction_year: { type: String },
  other_lastest_date: { type: String },
  other_interval: { type: String },
  other_next_date: { type: String },
  attendance_lastest_date: { type: String },
  attendance_interval: { type: String },
  attendance_next_date: { type: String },
  maintenance_lastest_date: { type: String },
  maintenance_interval: { type: String },
  attendance_interval_unit: { type: String },
  attendance_interval_value: { type: String },
  attendance_next_date: { type: String },
  maintenance_lastest_date: { type: String },
  maintenance_interval_unit: { type: String },
  maintenance_interval_value: { type: String },
  maintenance_next_date: { type: String },
  instruction_text: { type: String },
  remark_text: { type: String },
  inspection_interval_value: { type: String },
  inspection_next_date: { type: String },
  attribute_001: { type: String },
  attribute_002: { type: String },
  attribute_003: { type: String },
  attribute_004: { type: String },
  attribute_005: { type: String },
  attribute_006: { type: String },
  attribute_007: { type: String },
  attribute_008: { type: String },
  attribute_009: { type: String },
  attribute_010: { type: String },
  attribute_011: { type: String },
  attribute_012: { type: String },
  attribute_013: { type: String },
  attribute_014: { type: String },
  attribute_015: { type: String },
  attribute_016: { type: String },
  warranty_expire_date: { type: String },
  warranty_parts: { type: String },
  warranty_notes: { type: String },

  position_of_code: { type: String },
  u_system: { type: String },
  latitude: { type: String },
  longitude: { type: String },
  changed_by: { type: String },
  change_date: { type: String },

  component_name: { type: String },
  timeAttendance: { type: String },
  attendance_text: { type: String },
  timeMaintenance: { type: String },
  maintenance_text: { type: String },
  intervalClean: { type: String },
  timeClean: { type: String },
  cleaning_text: { type: String },
  attributes: { type: String },
  inspection_mandatory: { type: String },
  inspection_type: { type: String },
  inspection_latest: { type: String },
  // ....................
  owner: { type: String },
  installation_date: { type: String },
  technical_life_span: { type: String },
  status: { type: String },
  status_year: { type: String },
  attendance_budget_time_min: { type: String },
  other_budget_time_min: { type: String },
  maintenance_budget_time_min: { type: String },
  inspection_interval: { type: String },
  inspection_next_date: { type: String },
  inspection_interval_unit: { type: String },
  responsible_user: {
    type: String,
    set: (value) => value?.toLowerCase(),
  },
  image: {
    link: { type: String },
    createdAt: { type: Date, default: new Date() },
    format: { type: String },
    dimensions: { type: String },
    key: { type: String },
  },
  attendance_plan_date: { type: String },
  maintenance_plan_date: { type: String },
  order: {
    type: String,
  },
  long_name: {
    type: String,
  },
});

// Export
// export default mongoose.model("u_components", ComponentSchema);
export default mongoose.model("components", ComponentSchema);
