import express from "express";
import usersRouter from "./api/users.js";
import imagesRouter from "./api/images.js";
import buildingsRouter from "./api/buildings.js";
import componentsRouter from "./api/components.js";
import propertiesRouter from "./api/properties.js";
import activitiesRouter from "./api/activities.js";
import notificationsRouter from "./api/notifications.js";
import planningRouter from "./api/planning.js";
import maintainceItemsRouter from "./api/maintainceItems.js";
import maintaincePackageRouter from "./api/maintaincePackage.js";
import uSystemsRouter from "./api/uSystems.js";
import authRouter from "./api/auth.js";
import planningComponentRouter from "./api/planning/index.js";
import componentPackageRouter from "./api/componentPackage.js";
import maintenanceSettingsRouter from "./api/maintenanceSettings.js";
import maintenanceDepositionsRouter from "./api/maintenanceDepositions.js";
import uComponentsRouter from "./api/uComponents.js";
import supervisionRouter from "./api/supervision.js";
import UserAccountsRouter from "./api/userAccounts.js";
import { checkToken } from "../utils/authenticationToken.js";
import ImagesFilesRouter from "./api/imagesFiles.js";
import stripeController from "./api/stripeController.js";
import SettingPropertyRouter from "./api/settingProperty.js";
import SettingBuildingRouter from "./api/settingBuildings.js";
import SettingAddressesRouter from "./api/settingAddresses.js";
import RentalObjectsRouter from "./api/rentalObjects.js";
import OnBoardingRouter from "./api/onBoarding.js";
import MaintenanceReportRouter from "./api/maintenanceReport.js";
import landingRouter from "./api/landingRouter.js";
import bedrockRouter from "./api/bedrock.js";

const app = express();

app.get("/", (req, res) => {
  res.send("Janus backend");
  res.end();
});

app.use("/auth", authRouter);
app.use("/stripe", stripeController);
app.use("/landing", landingRouter);
app.use(checkToken);
app.use("/buildings", buildingsRouter);
app.use("/properties", propertiesRouter);
app.use("/images", imagesRouter);
app.use("/components", componentsRouter);
app.use("/component_package", componentPackageRouter);
app.use("/activities", activitiesRouter);
app.use("/notifications", notificationsRouter);
app.use("/users", usersRouter);
app.use("/plannings", planningRouter);
app.use("/maintaince_items", maintainceItemsRouter);
app.use("/maintaince_packages", maintaincePackageRouter);
app.use("/u_systems", uSystemsRouter);
app.use("/planning_component", planningComponentRouter);
app.use("/maintenance_settings", maintenanceSettingsRouter);
app.use("/maintenance_depositions", maintenanceDepositionsRouter);
app.use("/u_components", uComponentsRouter);
app.use("/supervision", supervisionRouter);
app.use("/useraccounts", UserAccountsRouter);
app.use("/images-files", ImagesFilesRouter);
app.use("/datasetting-property", SettingPropertyRouter);
app.use("/datasetting-buildings", SettingBuildingRouter);
app.use("/datasetting-addresses", SettingAddressesRouter);
app.use("/datasetting-rentalObjects", RentalObjectsRouter);
app.use("/onboarding", OnBoardingRouter);
app.use("/maintenance-report", MaintenanceReportRouter);
app.use("/buildings", buildingsRouter);
app.use("/bedrock", bedrockRouter);

export default app;
